"""add early bird pricing and registration review models

Revision ID: abf9866a1b52
Revises: 
Create Date: 2026-09-21 21:34:29.781679

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'abf9866a1b52'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_action_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('registration_id', sa.UUID(), nullable=False),
    sa.Column('admin_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.Enum('verified', 'rejected', name='admin_action_enum'), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['registration_id'], ['event_registrations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_action_logs_registration_id'), 'admin_action_logs', ['registration_id'], unique=False)
    op.create_index(op.f('ix_event_registrations_leader_id'), 'event_registrations', ['leader_id'], unique=False)
    op.add_column('events', sa.Column('early_bird_enabled', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('events', sa.Column('early_bird_capacity', sa.Integer(), nullable=True))
    op.add_column('events', sa.Column('early_bird_fee', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('events', sa.Column('early_bird_taken', sa.Integer(), server_default=sa.text('0'), nullable=False))
    op.create_index(op.f('ix_events_deleted_at'), 'events', ['deleted_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_events_deleted_at'), table_name='events')
    op.drop_column('events', 'early_bird_taken')
    op.drop_column('events', 'early_bird_fee')
    op.drop_column('events', 'early_bird_capacity')
    op.drop_column('events', 'early_bird_enabled')
    op.drop_index(op.f('ix_event_registrations_leader_id'), table_name='event_registrations')
    op.drop_index(op.f('ix_admin_action_logs_registration_id'), table_name='admin_action_logs')
    op.drop_table('admin_action_logs')
    # ### end Alembic commands ###
