"""add is_early_bird and fee_charged to event_registrations

Revision ID: d1161822aacd
Revises: abf9866a1b52
Create Date: 2026-09-22 01:06:18.254054

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1161822aacd'
down_revision: Union[str, None] = 'abf9866a1b52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_registrations', sa.Column('is_early_bird', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('event_registrations', sa.Column('fee_charged', sa.Numeric(precision=10, scale=2), nullable=True))
    op.execute("UPDATE event_registrations SET fee_charged = amount_paid WHERE fee_charged IS NULL")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event_registrations', 'fee_charged')
    op.drop_column('event_registrations', 'is_early_bird')
    # ### end Alembic commands ###
